### PR TITLE
Two+ players

### PR DESCRIPTION
**Pull request by mohammaduvez**
Added support for more then two players (Upto eight).

### CODE REVIEW

**Comment by ketanhwr** [comment]
Looks good for a start. Please indent your code properly (tabs/spaces). I've noticed a few bugs, let's see where this goes!

**Comment by avalan4e57** [comment]
Hey guys! How is it going? I want to close that issue. But if @mohammaduvez currently works on it then I'd better try smth else.

**Comment by mohammaduvez** [comment]
Here is some code clean up
@avalan4e57 if you want to improve or give your own solution then you can.

I want to use a playerMatrix[][] , but it affects others (like colorMatrix, count...etc..)

playerMatrix[][] would contain player identified by color and their status not-playing(0), playing not out(1) and out(2).

**Comment by avalan4e57** [comment]
@mohammaduvez thank you for invitation. I think we should better wait for @ketanhwr response before going any further with this stuff.

**Comment by ketanhwr** [comment]
Hey guys I'm a bit busy atm. @avalan4e57 maybe you can help with testing and reviewing as of now!

**Comment by avalan4e57** [comment]
@ketanhwr I didn't expect this but I'm also a bit busy. Maybe later.

**Comment by ketanhwr** [comment]
Thanks! :slightly_smiling_face:

**Pull request merged**
