### PR TITLE
added turn indcators

### PR DESCRIPTION
**Pull request by dcoollx**
also fixed issue where screen jumps with MS edge. added event.preventDefault(); to beginning of gameloop function

### CODE REVIEW

**Comment by paulotokimatu** [comment]
@ketanhwr  One question: why is git diff accusing that all lines were changed?

**Comment by ketanhwr** [comment]
Strange..let me look into it.

**Comment by ketanhwr** [comment]
Okay so here's the problem:
image

@dcoollx I guess you can see why the diff is so large. Please fix it and I'll review it then.

**Comment by dcoollx** [comment]
Is this because I used MS Visual Studios? I'll clone it again and fix this

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ketanhwr** [comment]
From what I know, these are added in Vim, but I guess it might have been added by MS Visual Studio as well. No need to clone it again, you can just switch all the `^M` to carriage returns and make another commit in the same branch.

**Comment by dcoollx** [comment]
Yeah I should have realized this might happen when you told me you were working in a Linux development environment. Windows uses a different EOL character. so when I opened it in VS it automatically changed it over. I found that if I use the GIT CLI it changes it back for me. but I'm not that skilled at using git from the CLI yet so I apologize because I ended up creating a new pull request. But at least that issue is fixed.

**Comment by ketanhwr** [comment]
Okay, I'll close this one and take a look into the other one.

**Pull request closed without merging**
